# Generated by Django 5.1.2 on 2024-10-24 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcatalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
