# Generated by Django 5.1.2 on 2024-10-24 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcatalog', '0003_remove_review_recipe_ratingreview_delete_rating_and_more'),
        ('main', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingreview',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='main.recipe'),
        ),
        migrations.AlterField(
            model_name='ratingreview',
            name='score',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
