# Generated by Django 5.1.2 on 2024-10-25 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcatalog', '0004_alter_ratingreview_recipe_alter_ratingreview_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingreview',
            name='score',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
