# Generated by Django 5.0.6 on 2024-10-23 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
