# Generated by Django 5.1.1 on 2024-10-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default-user.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
