# Generated by Django 5.1.4 on 2024-12-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artikel_images/'),
        ),
    ]
